on:
  push:
  pull_request:
      branches:
        - master
  workflow_dispatch:

name: Check links
jobs:
  check-links:
    name: Check links
    runs-on: ubuntu-latest
    steps:

      - name: Clone sources
        uses: actions/checkout@v2
        with:
          path: sources

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Check links in Mardown files
        run: |
          gem install awesome_bot
          cd sources
          awesome_bot README.md --skip-save-results
